{% set name = "jupyter_ydoc" %}
{% set version = "3.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-server/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8e164ccfc4a8f660117a3c7c7b0f70d951916c2a58a8dc603aad85764c5c6515

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.10.0
    - hatch-nodejs-version
  run:
    - python
    - pycrdt >=0.10.1,<0.13.0

# pytest needs hypercorn  and httpx-ws in conftest.py, which are not available.
test:
  imports:
    - jupyter_ydoc
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  description: jupyter_ydoc provides Ypy-based data structures for various documents used in the Jupyter ecosystem
  dev_url: https://github.com/jupyter-server/jupyter_ydoc
  doc_url: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart