{% set name = "jupyter_ydoc" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23948daf60a0c3c0a4b3715a66cb6ccad2de56694864842534fb1b1564b9b56b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - hatch-nodejs-version
    - python >=3.7
  run:
    - python >=3.7
    - importlib_metadata >=3.6
    - y-py >=0.5.3,<0.6.0

test:
  imports:
    - jupyter_ydoc

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  dev_url: https://github.com/jupyter-server/jupyter_ydoc

extra:
  recipe-maintainers:
    - davidbrochart
