{% set name = "jupyter_ydoc" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e09faa145bedbca714e06b22cfc4f7eab9f176d20e2ed8c80fd96e7e55080e6c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - setuptools
    - ypy-websocket >=0.1.2

test:
  imports:
    - jupyter_ydoc

about:
  home: https://github.com/davidbrochart/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  dev_url: https://github.com/davidbrochart/jupyter_ydoc

extra:
  recipe-maintainers:
    - davidbrochart
