{% set name = "jupyter_ydoc" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 262253469340100ae220ae46e0a2d26825b91a5a13be09628273a635692d8ce9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - setuptools
    - y-py >=0.5.3,<0.6.0

test:
  imports:
    - jupyter_ydoc

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  dev_url: https://github.com/jupyter-server/jupyter_ydoc

extra:
  recipe-maintainers:
    - davidbrochart
