{% set name = "jupyter_ydoc" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-server/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 69a9393204a1dc40798dac385a9aff50601d458c2280679f58a25070e5170987

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.10.0
    - hatch-nodejs-version
  run:
    - python
    - importlib-metadata >=3.6  # [py<310]
    - pycrdt >=0.10.1,<0.13.0

# pytest needs hypercorn  and httpx-ws in conftest.py, which are not available.
test:
  imports:
    - jupyter_ydoc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  description: jupyter_ydoc provides Ypy-based data structures for various documents used in the Jupyter ecosystem
  dev_url: https://github.com/jupyter-server/jupyter_ydoc
  doc_url: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
