{% set name = "jupyter_ydoc" %}
{% set version = "0.2.4" %}
{% set sha256 = "a3f670a69135e90493ffb91d6788efe2632bf42c6cc42a25f25c2e6eddd55a0e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  # y-py not available for s390x
  skip: true # [s390x or py<37]

requirements:
  host:
    - hatch-nodejs-version
    - hatchling >=1.12.0
    - pip
    - python
    - wheel
  run:
    - python
    - importlib_metadata >=3.6 # [py<310]
    - y-py >=0.5.3,<0.6.0

test:
  imports:
    - jupyter_ydoc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  description: jupyter_ydoc provides Ypy-based data structures for various documents used in the Jupyter ecosystem
  dev_url: https://github.com/jupyter-server/jupyter_ydoc
  doc_url: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
