{% set name = "jupyter_ydoc" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3163bd4745eedd46d4bba6df52ab26be3c5c44c3a8aaf247635062486ea8f84f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python >=3.7
  run:
    - python >=3.7
    - importlib_metadata >=3.6
    - y-py >=0.5.3,<0.6.0

test:
  imports:
    - jupyter_ydoc

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  dev_url: https://github.com/jupyter-server/jupyter_ydoc

extra:
  recipe-maintainers:
    - davidbrochart
