{% set name = "jupyter_ydoc" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-server/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2509e19df2a34401e9aca6a25279dc3e88ac8dc9591a3369c7eb5aad61c49a7f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.10.0
    - hatch-nodejs-version
  run:
    - python
    - importlib-metadata >=3.6  # [py<310]
    - pycrdt >=0.10.1,<0.13.0

# pytest needs hypercorn in conftest.py, which is not available.
test:
  imports:
    - jupyter_ydoc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  description: jupyter_ydoc provides Ypy-based data structures for various documents used in the Jupyter ecosystem
  dev_url: https://github.com/jupyter-server/jupyter_ydoc
  doc_url: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
