{% set name = "jupyter_ydoc" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2fdbbe6c9a095ddd1997480af1a72735f12aa754fe0958dfdb0e2765ca0086ef

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - setuptools
    - y-py >=0.5.2,<0.6.0
    - ypy-websocket >=0.1.8

test:
  imports:
    - jupyter_ydoc

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Document structures for collaborative editing using Ypy
  dev_url: https://github.com/jupyter-server/jupyter_ydoc

extra:
  recipe-maintainers:
    - davidbrochart
